name: Deploy example site preview

on:
  pull_request:
    branches: [main]

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    environment:
      name: "#${{ github.event.number }}: Example site preview"
      url: ${{ steps.deploy-preview.outputs.preview-url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: npm

      - name: Build and pack package
        if: github.event.action != 'closed'
        run: |
          npm ci
          npm run build
          npm pack

      - name: Install and Build
        if: github.event.action != 'closed' # You might want to skip the build if the PR has been closed
        run: |
          cd example
          npm add ../swarpc-*.tgz
          npm install 
          BUILD_COMMIT=${{ github.sha }} BASE_PATH=/cigale/_pullrequests/pr-$PR_NUMBER npm run build
        env:
          PR_NUMBER: ${{ github.event.number }}

      - name: Deploy preview
        id: deploy-preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./example/build
          umbrella-dir: _pullrequests
          comment: false
